const baseUrl = import.meta.env.BASE_URL || '/';

const SOUND_MAP = {
  pickup: `${baseUrl}pickup.wav`,
  menuPress: `${baseUrl}SoundEffects/menuPresser.mp3`,
  ambient: `${baseUrl}SoundEffects/dark-horror-ambience-296781.mp3`,
  openingDoor: `${baseUrl}SoundEffects/opening_door.mp3`,
  creakingDoor: `${baseUrl}SoundEffects/creaking-door-41706.mp3`,
  lockedDoor: `${baseUrl}SoundEffects/trying-to-open-a-locked-door-104302.mp3`,
  quizDoor: `${baseUrl}SoundEffects/QuizDoor.mp3`,
  safeOpen: `${baseUrl}SoundEffects/Safe_opening.mp3`,
  correct: `${baseUrl}SoundEffects/CorrectButton.mp3`,
  alarm: `${baseUrl}SoundEffects/alarm-301729.mp3`,
  footsteps: `${baseUrl}SoundEffects/heavy-walking-footsteps-352771.mp3`,
  monsterRoar: `${baseUrl}SoundEffects/low-monster-roar-97413.mp3`,
  rowing: `${baseUrl}SoundEffects/rowingMachine.mp3`,
  xpLevel: `${baseUrl}SoundEffects/XpLevelUp.mp3`,
};

export function playSound(name = 'pickup', opts = {}) {
  const src = SOUND_MAP[name] || SOUND_MAP.pickup;
  const audio = new Audio(src);
  audio.volume = opts.volume !== undefined ? opts.volume : 0.5;
  if (opts.loop) audio.loop = true;
  audio.play().catch(() => {});
  return audio;
}

export function stopSound(audio) {
  if (audio) {
    audio.pause();
  }
}

export function attachButtonSound() {
  document.addEventListener(
    'click',
    (e) => {
      if (e.target.tagName === 'BUTTON') {
        playSound('menuPress', { volume: 0.3 });
      }
    },
    true
  );
}

// Play a voice over audio clip generated by Bark
export function playVoice(filePath) {
  const audio = new Audio(filePath);
  audio.volume = 1.0;
  audio.play().catch(() => {});
}

// Speak the provided text using Google Text-to-Speech REST API
// Requires VITE_GOOGLE_TTS_KEY environment variable containing an API key
export async function speakText(text) {
  if (typeof fetch === 'undefined') return;
  const apiKey = import.meta.env.VITE_GOOGLE_TTS_KEY;
  if (!apiKey) {
    if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = 'en-GB';
      utterance.rate = 0.8;
      window.speechSynthesis.speak(utterance);
    }
    return;
  }

  try {
    const response = await fetch(
      `https://texttospeech.googleapis.com/v1/text:synthesize?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          input: { text },
          voice: {
            languageCode: 'en-GB',
            name: 'en-GB-Wavenet-B',
            ssmlGender: 'MALE',
          },
          audioConfig: { audioEncoding: 'MP3', speakingRate: 0.8 },
        }),
      }
    );

    const data = await response.json();
    if (data.audioContent) {
      const audio = new Audio(`data:audio/mp3;base64,${data.audioContent}`);
      audio.play().catch(() => {});
    }
  } catch (err) {
    console.error('Failed to speak text with Google TTS', err);
    if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = 'en-GB';
      utterance.rate = 0.8;
      window.speechSynthesis.speak(utterance);
    }
  }
}

/**
 * Estimate calories burned using MET, weight, and duration or reps/sets.
 * @param {Object} exercise - The exercise object (must include `met`)
 * @param {number} userWeightKg - Student weight in kg (default = 50)
 * @param {number} durationMin - For cardio or time-based movements
 * @param {number} sets - For strength exercises
 * @param {number} reps - For strength exercises
 * @param {number} weightLiftedPerRep - In kg (for weighted strength moves)
 * @returns {number} Estimated calories burned
 */
export function estimateCalories({
  exercise,
  userWeightKg = 50,
  durationMin = 0,
  sets = 0,
  reps = 0,
  weightLiftedPerRep = 0,
}) {
  const met = exercise.met || 0;

  if (durationMin > 0) {
    // Cardio or timed movement
    return +(met * userWeightKg * (durationMin / 60)).toFixed(1);
  }

  if (sets > 0 && reps > 0) {
    const estimatedTimeMin = (sets * reps * 3) / 60; // Assume ~3 seconds per rep
    const adjustedMet = met || 4.0;
    return +(adjustedMet * userWeightKg * (estimatedTimeMin / 60)).toFixed(1);
  }

  return 0; // Unknown case
}
